#!/bin/bash

clear;

CURDIR=$(pwd);

if [ $# -eq 0 ]
then
    echo "arg count 0";
    ARGDIR=$CURDIR;
else
    if [ $# -eq 1 ]
    then
        echo "arg count 1";
        ARGDIR=$1$(ls "$1");
    else
        echo "arg count > 1";
        ARGDIR=$*;
    fi
fi

#echo "ARGDIR: '$ARGDIR'";
#echo "CURDIR: '$CURDIR'";

for dir in $ARGDIR; 
do
    if [ -d $dir ]
    then
        echo -n "Check directory $dir... ";
        cd "$dir";
        if [ -d ".git" ]
        then
            echo -e "\nExecuting commands into repository... ";
            git pull;
        else
            echo -e "not a git repository, skip!";
        fi;
        cd ..;
    else
        echo "Invalid directory argument: '$dir', skip!";
    fi
done;

exit 0;
