#!/bin/bash

clear;

CURDIR=$(pwd);
BASEDIR="";

if [ $# -eq 0 ]
then
    echo "arg count 0";
    ARGDIR=$CURDIR;
else
    if [ $# -eq 1 ]
    then
        echo "arg count 1";
        BASEDIR=$1;
        ARGDIR=$(ls "$1");
    else
        echo "arg count > 1";
        ARGDIR=$*;
    fi
fi

echo "ARGDIR: '$ARGDIR'";
echo "CURDIR: '$CURDIR'";

for directory in $ARGDIR; 
do
    directory=$BASEDIR$directory;
    if [ -d $directory ]
    then
        echo -e "[\033[1;32m OK \033[0m] Check directory $directory... ";
        if eval "cd $directory"
        then
            if [ -d ".git" ]
            then
                echo -e "[\033[1;32m OK \033[0m] Executing commands into repository... ";
                git pull;
            else
                echo -e "[\033[1;31m KO \033[0m] Directory '$directory' not is a valid git repository, skip!";
            fi;
            cd -;
        fi
    else
        echo -e "[\033[1;31m KO \033[0m] Invalid directory argument: '$directory', skip!";
    fi
done;

exit 0;
