#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  projectDeploy
#
#  Version 2.0
#
#  Copyright 2014 - 2015 Claudio Giordano <claudio.giordano@autistici.org>
#
#  Homepage https://github.com/clagiordano/gitScripts.git
#  Homepage https://clagiordano@bitbucket.org/clagiordano/gitscripts.git
#
#  License GPLv3 https://www.gnu.org/licenses/gpl.html

import sys
import os
import tempfile
import ConfigParser
from optparse import OptionParser

# Configuration class for ProjectDeploy
class ProjectDeployConfiguration(object):
    # Tempfile for rsync output and dialog configuration
    tempFile = tempfile.mkstemp()[1];
    dialogTempFile = tempfile.mkstemp()[1];

    # Script name configuration
    #~ scriptName = __file__
    scriptName = "projectDeploy"

    # Path configuration
    basePath = os.environ['HOME'] + "/." + scriptName
    logPath = basePath + "/." + scriptName + ".log"
    configPath = basePath + "/." + scriptName + ".conf"
    defaultProjectsRoot = "/tmp"

    # Projects file configurations with default value
    syncPreFile          = "pre-sync"
    syncPostFile         = "post-sync"
    syncIgnoresFile      = "ignores"
    syncTargetsFile      = "targets"
    syncMultiTargetsFile = "multitargets"
    syncExtraOptions     = "rsync-extra"
    
    # Switch configuration
    dialogMode = False
    verboseMode = False
    debugMode = False
    multitargetMode = False
    multitargetModeAvailable = False

    # Messages configurations
    dialogTitle = "Choose a project to deploy from"
    deployMsg = "Choose a project's number to deploy or 0 to abort: "
    deployAbortMsg = "Deploy aborted."
    deploySelectFromListMsg = "Select an element from list or 0 to abort: "

    # NOTE: Option info none only suppported from rsync protocol v.31
    # Classic output verbose with percentage progress for single file
    rsyncOptions = "-arvzhi --progress --delete"
    # Solo output avanzamento globale, %, velocità e stats finali al termine
    rsyncOptions = "-arzh --info=none,progress2,stats --delete"
    # Solo output avanzamento globale, % e velocità
    rsyncOptions = "-arzhvi --info=progress2 --delete"

    # Dialog config
    # Auto-size with height and width = 0. Maximize with height and width = -1.
    dialogType = "menu"
    dialogMenuHeight = 0
    dialogMenuWidth = 0
    dialogMenuMenuHeight = 0


class ProjectDeploy(object):
    def setDefaultConfig(self):
        # Create base config object
        self.Configuration = ProjectDeployConfiguration();        
        
        #~ print self.Configuration
    
    def usageOutput(self):
        print "Usage: %s [ OPTIONS ]" % __file__;
        print "\t -d \t\t Enable dialog mode.";
        print "\t -v \t\t Verbose output.";
        print "\t -t \t\t Enable text mode.";
        print "\t -r PATH\t Change projects root.";
        print "\t -h \t\t Print this help.";
        print "\t -b \t\t Enable debug mode.";
        print "\t -m \t\t Enable multi target mode.";

    def parseArgs():
        pass

    def error(self, message):
        print "[\033[1;31mERROR\033[0m      ]: " + message;
        
    def success(self, message):
        print "[\033[1;32mSUCCESS\033[0m    ]: " + message;
        
    def warning(self, message):
        print "[\033[1;33mWARNING\033[0m    ]: " + message;
        
    def debug(self, message):
        if (self.Configuration.debugMode == True):
            #echo -e "[\033[0;35mDEBUG\033[0m      ]: \033[0;35m$1\033[0m" 1>&2;  # Redirige lo stdout su stderr
            print "\033[1;30m[DEBUG      ]: $1\033[0m" 1>&2  # Redirige lo stdout su stderr
        
        

    def __init__(self):
        self.setDefaultConfig()
        self.usageOutput()
        self.debug("TEST 1")
        self.Configuration.debugMode = True
        self.debug("TEST 2")

if __name__ == "__main__":
    projectdeploy = ProjectDeploy()
