#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  projectDeploy
#
#  Version 2.0
#
#  Copyright 2014 - 2015 Claudio Giordano <claudio.giordano@autistici.org>
#
#  Homepage https://github.com/clagiordano/gitScripts.git
#  Homepage https://clagiordano@bitbucket.org/clagiordano/gitscripts.git
#
#  License GPLv3 https://www.gnu.org/licenses/gpl.html

import sys
import os
import tempfile
import ConfigParser
import argparse

# Configuration class for ProjectDeploy
class ProjectDeployConfiguration(object):
    # Tempfile for rsync output and dialog configuration
    tempFile = tempfile.mkstemp()[1];
    dialogTempFile = tempfile.mkstemp()[1];

    # Script name configuration
    #~ scriptName = __file__
    scriptName = "projectDeploy"

    # Path configuration
    basePath = os.environ['HOME'] + "/." + scriptName
    logPath = basePath + "/." + scriptName + ".log"
    configPath = basePath + "/." + scriptName + ".conf"
    defaultProjectsRoot = "/tmp"

    # Projects file configurations with default value
    syncPreFile          = "pre-sync"
    syncPostFile         = "post-sync"
    syncIgnoresFile      = "ignores"
    syncTargetsFile      = "targets"
    syncMultiTargetsFile = "multitargets"
    syncExtraOptions     = "rsync-extra"
    
    # Switch configuration
    dialogMode = False
    verboseMode = False
    debugMode = False
    multitargetMode = False
    multitargetModeAvailable = False

    # Messages configurations
    dialogTitle = "Choose a project to deploy from"
    deployMsg = "Choose a project's number to deploy or 0 to abort: "
    deployAbortMsg = "Deploy aborted."
    deploySelectFromListMsg = "Select an element from list or 0 to abort: "

    # NOTE: Option info none only suppported from rsync protocol v.31
    # Classic output verbose with percentage progress for single file
    rsyncOptions = "-arvzhi --progress --delete"
    # Solo output avanzamento globale, %, velocità e stats finali al termine
    rsyncOptions = "-arzh --info=none,progress2,stats --delete"
    # Solo output avanzamento globale, % e velocità
    rsyncOptions = "-arzhvi --info=progress2 --delete"

    # Dialog config
    # Auto-size with height and width = 0. Maximize with height and width = -1.
    dialogType = "menu"
    dialogMenuHeight = 0
    dialogMenuWidth = 0
    dialogMenuMenuHeight = 0


class ProjectDeploy(object):
    def setDefaultConfig(self):
        # Create base config object
        self.Configuration = ProjectDeployConfiguration();        
        
        #~ print self.Configuration
    
    def usageOutput(self):
        pass
        

    def error(self, message):
        print "[\033[1;31mERROR\033[0m      ]: " + message;
        
    def success(self, message):
        print "[\033[1;32mSUCCESS\033[0m    ]: " + message;
        
    def warning(self, message):
        print "[\033[1;33mWARNING\033[0m    ]: " + message;
        
    def debug(self, message):
        if (self.Configuration.debugMode == True):
            print "\033[1;30m[DEBUG      ]: %s\033[0m" % message

    ##
    # Write a message to logfile
    #
    def log2file(self, message):
        #echo "[$(date +'%Y-%m-%d %H:%M:%S')]: $*" >> "${CONFIG_LOG_PATH}";
        pass
        
    def setArgParser(self):
        parser = argparse.ArgumentParser()
        #~ print "\t -d \t\t Enable dialog mode.";
        parser.add_argument("-v", "--verbose", action='store_true', help="Enable verbose output")
        parser.add_argument("-t", "--text", action='store_true', help="Enable text output")
        parser.add_argument("-b", "--debug", action='store_true', help="Enable debug output")
        parser.add_argument("-m", "--multitarget", action='store_true', help="Enable multi target mode")
        parser.add_argument("-r", "--root", help="Change projects root")
        
        #~ print "\t -r PATH\t Change projects root.";
        #~ parser.add_argument('-f', '--foo', action='store_true')
        args = parser.parse_args()
        print "[Debug]: %s" % args

    def __init__(self):
        self.setArgParser()
        self.setDefaultConfig()
        self.usageOutput()

if __name__ == "__main__":
    projectdeploy = ProjectDeploy()
